# Generated by Django 5.0.3 on 2024-04-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('provider', models.CharField(max_length=100)),
                ('review', models.CharField()),
            ],
        ),
    ]
