# Generated by Django 5.0.3 on 2024-04-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField()),
                ('epiosde', models.PositiveSmallIntegerField()),
                ('date', models.DateField(verbose_name='Viewing Date')),
                ('stars', models.IntegerField(choices=[(0, 'Zero Stars'), (1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars')])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tvshow')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
