# Generated by Django 5.0.3 on 2024-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_viewing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tvshow',
            name='actors',
            field=models.ManyToManyField(to='main_app.cast'),
        ),
    ]
